openapi: 3.0.0
info:
  title: Bursar export
  version: v1
servers:
  - url: /tenant/
paths:
  /bursar-export-config:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/scheduleConfiguration"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Get a list of existing validation rules for a tenant
      operationId: getTenantRules
    post:
      responses:
        '201':
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: good
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: Bad request
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Add schedule configuration
      operationId: postTenantRules
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/scheduleConfiguration"
        required: true
components:
  schemas:
    scheduleConfiguration:
      $ref: schemas/scheduleConfiguration.json
